import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { extname, join, relative, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import robots from "@/app/robots";
import sitemap from "@/app/sitemap";
import { shipments } from "@/data/shipments";
import { appNav, footerNav, publicNav } from "@/content/navigation";

const ROOT = resolve(process.cwd());
const APP = join(ROOT, "src", "app");
const SRC = join(ROOT, "src");

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

/** Derives the route patterns from the filesystem, ignoring route groups. */
function routePatterns(): string[] {
  return walk(APP)
    .filter((file) => /[/\\]page\.tsx$/.test(file))
    .map((file) => {
      const segments = relative(APP, file)
        .replace(/[/\\]page\.tsx$/, "")
        .split(/[/\\]/)
        .filter((segment) => segment.length > 0 && !/^\(.*\)$/.test(segment));
      return `/${segments.join("/")}`;
    })
    .map((route) => (route === "/" ? "/" : route.replace(/\/$/, "")))
    .sort();
}

const PATTERNS = routePatterns();

const PUBLIC_ROUTES = [
  "/",
  "/about",
  "/contact",
  "/coverage",
  "/services",
  "/solutions",
  "/tracking",
  "/tracking/[trackingNumber]",
];

const PRIVATE_ROUTES = [
  "/analytics",
  "/customers",
  "/dashboard",
  "/login",
  "/settings",
  "/shipments",
  "/shipments/[id]",
];

describe("route structure", () => {
  it("contains exactly the documented routes", () => {
    expect(PATTERNS).toEqual([...PUBLIC_ROUTES, ...PRIVATE_ROUTES].sort());
  });

  it("stays intentionally compact", () => {
    expect(PATTERNS.length).toBeGreaterThanOrEqual(14);
    expect(PATTERNS.length).toBeLessThanOrEqual(20);
  });

  it("ships the generated metadata routes", () => {
    for (const file of [
      "sitemap.ts",
      "robots.ts",
      "manifest.ts",
      "opengraph-image.tsx",
      "icon.svg",
      "not-found.tsx",
      "globals.css",
      "layout.tsx",
    ]) {
      expect(existsSync(join(APP, file)), `missing src/app/${file}`).toBe(true);
    }
  });
});

describe("internal links", () => {
  /** Matches a route pattern, treating `[param]` as a single path segment. */
  const matches = (href: string) =>
    PATTERNS.some((pattern) => {
      const regex = new RegExp(
        `^${pattern
          .split("/")
          .map((segment) =>
            /^\[.+\]$/.test(segment) ? "[^/]+" : segment.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"),
          )
          .join("/")}$`,
      );
      return regex.test(href);
    });

  const sourceFiles = walk(SRC).filter((file) => [".ts", ".tsx"].includes(extname(file)));

  it("all point at a route that exists", () => {
    const dead: string[] = [];

    for (const file of sourceFiles) {
      const content = readFileSync(file, "utf8");
      for (const match of content.matchAll(/href="(\/[^"]*)"/g)) {
        const href = match[1].split(/[?#]/)[0].replace(/\/$/, "") || "/";
        // Static assets served from /public or generated by the app router.
        if (/\.(svg|png|ico|xml|txt|webmanifest)$/.test(href)) continue;
        if (!matches(href)) dead.push(`${relative(ROOT, file)} → ${href}`);
      }
    }

    expect(dead).toEqual([]);
  });

  it("are covered by the navigation content files", () => {
    const navHrefs = [
      ...publicNav.map((item) => item.href),
      ...appNav.map((item) => item.href),
      ...footerNav.flatMap((group) => group.links.map((link) => link.href)),
    ];
    for (const href of navHrefs) expect(matches(href as string)).toBe(true);
  });

  it("include every primary route in the public navigation or footer", () => {
    const reachable = new Set<string>([
      "/",
      ...publicNav.map((item) => String(item.href)),
      ...appNav.map((item) => String(item.href)),
      ...footerNav.flatMap((group) => group.links.map((link) => String(link.href))),
    ]);
    for (const route of PATTERNS) {
      if (route.includes("[")) continue; // reached from its index page
      expect(reachable.has(route), `${route} is not linked from navigation`).toBe(true);
    }
  });
});

describe("sitemap", () => {
  const entries = sitemap();
  const paths = entries.map((entry) => new URL(entry.url).pathname);

  it("lists every public route", () => {
    for (const route of PUBLIC_ROUTES) {
      if (route.includes("[")) continue;
      expect(paths).toContain(route);
    }
  });

  it("lists a tracking page for every shipment", () => {
    for (const shipment of shipments) {
      expect(paths).toContain(`/tracking/${shipment.trackingNumber}`);
    }
  });

  it("excludes every private application route", () => {
    for (const route of PRIVATE_ROUTES) {
      if (route.includes("[")) continue;
      expect(paths).not.toContain(route);
    }
  });

  it("has no duplicates and uses absolute URLs", () => {
    expect(new Set(entries.map((entry) => entry.url)).size).toBe(entries.length);
    for (const entry of entries) expect(entry.url).toMatch(/^https?:\/\//);
  });
});

describe("robots", () => {
  const result = robots();
  const rule = Array.isArray(result.rules) ? result.rules[0] : result.rules;
  const disallow = [rule?.disallow ?? []].flat();

  it("disallows every private application route", () => {
    for (const route of PRIVATE_ROUTES) {
      if (route.includes("[")) continue;
      expect(disallow).toContain(route);
    }
  });

  it("points at the sitemap", () => {
    expect(result.sitemap).toMatch(/\/sitemap\.xml$/);
  });
});

describe("page metadata", () => {
  const pages = walk(APP).filter((file) => /[/\\]page\.tsx$/.test(file));

  it("every page declares metadata", () => {
    const missing = pages
      .filter((file) => {
        const content = readFileSync(file, "utf8");
        return (
          !/export const metadata/.test(content) &&
          !/export async function generateMetadata/.test(content)
        );
      })
      .map((file) => relative(ROOT, file));
    expect(missing).toEqual([]);
  });

  it("marks every private route noIndex", () => {
    const leaking = pages
      .filter((file) => {
        const route = `/${relative(APP, file)
          .replace(/[/\\]page\.tsx$/, "")
          .split(/[/\\]/)
          .filter((segment) => segment.length > 0 && !/^\(.*\)$/.test(segment))
          .join("/")}`;
        if (!PRIVATE_ROUTES.includes(route)) return false;
        return !/noIndex: true|index: false/.test(readFileSync(file, "utf8"));
      })
      .map((file) => relative(ROOT, file));
    expect(leaking).toEqual([]);
  });

  it("gives the 404 page noindex and emits no canonical link", () => {
    const content = readFileSync(join(APP, "not-found.tsx"), "utf8");
    expect(content).toMatch(/index: false/);
    // `alternates` is the only way a canonical URL reaches the document.
    expect(content).not.toMatch(/alternates/);
    // It must not route through createMetadata either, which would add one.
    expect(content).not.toMatch(/createMetadata/);
  });

  it("declares exactly one h1 per page component", () => {
    const offenders = pages
      .map((file) => ({ file, content: readFileSync(file, "utf8") }))
      .filter(({ content }) => (content.match(/<h1[\s>]/g) ?? []).length > 1)
      .map(({ file }) => relative(ROOT, file));
    expect(offenders).toEqual([]);
  });
});
