"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useReducer,
  useSyncExternalStore,
  type ReactNode,
} from "react";
import type { RangeId } from "@/data/analytics";
import type { ProofOfDelivery, Shipment, ShipmentStatus, TrackingEvent } from "@/data/types";
import type { ShipmentMutation } from "@/lib/shipments";

/**
 * The demo store.
 *
 * There is no backend, so this holds the small amount of state that has to
 * survive navigation and reload: the demo session, local shipment edits, notes
 * and preferences. It deliberately does *not* hold the dataset — Server
 * Components render records from `src/data` and the overrides below are merged
 * on top, which keeps client bundles small and keeps one source of truth.
 */

export const DEMO_STORAGE_KEY = "parcel:demo:v1";

/** Caps so browser storage never grows without bound. */
const MAX_EVENTS_PER_SHIPMENT = 40;
const MAX_NOTES_PER_SHIPMENT = 30;
const MAX_RECENT_TRACKING = 6;

export type ShipmentPatch = {
  status?: ShipmentStatus;
  eta?: string;
};

export type LocalNote = { id: string; at: string; author: string; body: string };

export type NotificationPrefs = {
  exceptions: boolean;
  delays: boolean;
  outForDelivery: boolean;
  deliveryConfirmations: boolean;
  weeklySummary: boolean;
};

export type Preferences = {
  /** Table row height in the workspace. */
  density: "comfortable" | "compact";
  /** Range the analytics screen opens on. */
  defaultRange: RangeId;
  /** Whether the demo notices are shown. They can be turned off for screenshots. */
  showDemoNotices: boolean;
};

export type DemoState = {
  version: 1;
  signedIn: boolean;
  shipments: Record<string, ShipmentPatch>;
  /** Events appended locally, per shipment id. */
  events: Record<string, TrackingEvent[]>;
  /** Proof of delivery generated by "mark delivered". */
  pods: Record<string, ProofOfDelivery>;
  notes: Record<string, LocalNote[]>;
  notifications: NotificationPrefs;
  preferences: Preferences;
  profile: { name: string; email: string; role: string };
  /** Tracking numbers looked up in this browser, newest first. */
  recentTracking: string[];
};

export const initialDemoState: DemoState = {
  version: 1,
  signedIn: false,
  shipments: {},
  events: {},
  pods: {},
  notes: {},
  notifications: {
    exceptions: true,
    delays: true,
    outForDelivery: false,
    deliveryConfirmations: true,
    weeklySummary: false,
  },
  preferences: {
    density: "comfortable",
    defaultRange: "30d",
    showDemoNotices: true,
  },
  profile: { name: "", email: "", role: "" },
  recentTracking: [],
};

export type DemoAction =
  | { type: "hydrate"; state: DemoState }
  | { type: "reset" }
  | { type: "sign-in" }
  | { type: "sign-out" }
  | { type: "apply-mutation"; shipmentId: string; mutation: ShipmentMutation }
  | { type: "add-note"; shipmentId: string; note: LocalNote }
  | { type: "delete-note"; shipmentId: string; noteId: string }
  | { type: "record-tracking"; trackingNumber: string }
  | { type: "set-notifications"; patch: Partial<NotificationPrefs> }
  | { type: "set-preferences"; patch: Partial<Preferences> }
  | { type: "set-profile"; patch: Partial<DemoState["profile"]> };

/** Exported for unit tests — the demo store's entire behaviour lives here. */
export function demoReducer(state: DemoState, action: DemoAction): DemoState {
  switch (action.type) {
    case "hydrate":
      return action.state;
    case "reset":
      return initialDemoState;
    case "sign-in":
      return { ...state, signedIn: true };
    case "sign-out":
      return { ...state, signedIn: false };
    case "apply-mutation": {
      const { shipmentId, mutation } = action;
      const existing = state.events[shipmentId] ?? [];
      return {
        ...state,
        shipments: {
          ...state.shipments,
          [shipmentId]: { ...state.shipments[shipmentId], status: mutation.status },
        },
        events: {
          ...state.events,
          [shipmentId]: [...existing, mutation.event].slice(-MAX_EVENTS_PER_SHIPMENT),
        },
        pods: mutation.proofOfDelivery
          ? { ...state.pods, [shipmentId]: mutation.proofOfDelivery }
          : state.pods,
      };
    }
    case "add-note": {
      const existing = state.notes[action.shipmentId] ?? [];
      return {
        ...state,
        notes: {
          ...state.notes,
          [action.shipmentId]: [action.note, ...existing].slice(0, MAX_NOTES_PER_SHIPMENT),
        },
      };
    }
    case "delete-note": {
      const existing = state.notes[action.shipmentId] ?? [];
      return {
        ...state,
        notes: {
          ...state.notes,
          [action.shipmentId]: existing.filter((note) => note.id !== action.noteId),
        },
      };
    }
    case "record-tracking": {
      const next = [
        action.trackingNumber,
        ...state.recentTracking.filter((value) => value !== action.trackingNumber),
      ].slice(0, MAX_RECENT_TRACKING);
      return { ...state, recentTracking: next };
    }
    case "set-notifications":
      return { ...state, notifications: { ...state.notifications, ...action.patch } };
    case "set-preferences":
      return { ...state, preferences: { ...state.preferences, ...action.patch } };
    case "set-profile":
      return { ...state, profile: { ...state.profile, ...action.patch } };
    default:
      return state;
  }
}

/* ------------------------------------------------------------------ *
 * Merging
 * ------------------------------------------------------------------ */

/**
 * Applies local demo edits on top of an authored shipment.
 *
 * Exported (and unit-tested) because this is the function that guarantees
 * public tracking and the operations workspace still agree after a local
 * change: both call it with the same base record and the same state.
 */
export function resolveShipment(base: Shipment, state: DemoState): Shipment {
  const patch = state.shipments[base.id];
  const extraEvents = state.events[base.id];
  const localNotes = state.notes[base.id];
  const localPod = state.pods[base.id];

  if (!patch && !extraEvents && !localNotes && !localPod) return base;

  const events = extraEvents ? [...base.events, ...extraEvents] : base.events;
  const last = events[events.length - 1];

  return {
    ...base,
    status: patch?.status ?? base.status,
    eta: patch?.eta ?? base.eta,
    // Derived from the merged history, exactly as in the authored dataset.
    currentLocation: last ? last.location : base.currentLocation,
    events,
    proofOfDelivery: localPod ?? base.proofOfDelivery,
    notes: localNotes ? [...localNotes, ...base.notes] : base.notes,
  };
}

export function resolveShipments(base: Shipment[], state: DemoState): Shipment[] {
  return base.map((shipment) => resolveShipment(shipment, state));
}

/* ------------------------------------------------------------------ *
 * Provider
 * ------------------------------------------------------------------ */

type DemoContextValue = {
  state: DemoState;
  dispatch: (action: DemoAction) => void;
  /** False until browser storage has been read; use it to avoid hydration mismatches. */
  hydrated: boolean;
  resetDemo: () => void;
};

const DemoContext = createContext<DemoContextValue | null>(null);

/**
 * `true` only once the client has taken over rendering. Modelled as an external
 * store so no effect has to flip a state flag during hydration.
 */
const noopSubscribe = () => () => {};
const clientSnapshot = () => true;
const serverSnapshot = () => false;

export function DemoProvider({ children }: { children: ReactNode }) {
  const [state, dispatch] = useReducer(demoReducer, initialDemoState);
  const hydrated = useSyncExternalStore(noopSubscribe, clientSnapshot, serverSnapshot);

  // Load persisted demo state once, after hydration.
  useEffect(() => {
    try {
      const raw = window.localStorage.getItem(DEMO_STORAGE_KEY);
      if (!raw) return;
      const parsed = JSON.parse(raw) as DemoState;
      if (parsed && parsed.version === 1) {
        dispatch({ type: "hydrate", state: { ...initialDemoState, ...parsed } });
      }
    } catch {
      // Corrupt or unavailable storage simply starts from the seeded demo state.
    }
  }, []);

  useEffect(() => {
    if (!hydrated) return;
    try {
      window.localStorage.setItem(DEMO_STORAGE_KEY, JSON.stringify(state));
    } catch {
      // Ignore quota / private-mode errors — the demo still works in memory.
    }
  }, [state, hydrated]);

  const resetDemo = useCallback(() => {
    try {
      window.localStorage.removeItem(DEMO_STORAGE_KEY);
    } catch {
      // Nothing to clean up if storage is unavailable.
    }
    dispatch({ type: "reset" });
  }, []);

  const value = useMemo(
    () => ({ state, dispatch, hydrated, resetDemo }),
    [state, hydrated, resetDemo],
  );

  return <DemoContext.Provider value={value}>{children}</DemoContext.Provider>;
}

export function useDemo(): DemoContextValue {
  const context = useContext(DemoContext);
  if (!context) throw new Error("useDemo must be used inside <DemoProvider>");
  return context;
}

/* ------------------------------------------------------------------ *
 * Focused hooks
 * ------------------------------------------------------------------ */

export function useSession() {
  const { state, dispatch, hydrated } = useDemo();
  return {
    signedIn: state.signedIn,
    hydrated,
    signIn: () => dispatch({ type: "sign-in" }),
    signOut: () => dispatch({ type: "sign-out" }),
  };
}

/** A single shipment with local edits applied, plus the actions that change it. */
export function useShipment(base: Shipment) {
  const { state, dispatch, hydrated } = useDemo();
  const shipment = useMemo(() => resolveShipment(base, state), [base, state]);

  const apply = useCallback(
    (mutation: ShipmentMutation | null) => {
      if (!mutation) return;
      dispatch({ type: "apply-mutation", shipmentId: base.id, mutation });
    },
    [dispatch, base.id],
  );

  const addNote = useCallback(
    (body: string, author: string) => {
      dispatch({
        type: "add-note",
        shipmentId: base.id,
        note: {
          id: `${base.id}-note-local-${Date.now()}`,
          at: new Date().toISOString(),
          author,
          body,
        },
      });
    },
    [dispatch, base.id],
  );

  const deleteNote = useCallback(
    (noteId: string) => dispatch({ type: "delete-note", shipmentId: base.id, noteId }),
    [dispatch, base.id],
  );

  return { shipment, hydrated, apply, addNote, deleteNote };
}

/** A list of shipments with local edits applied. */
export function useShipments(base: Shipment[]) {
  const { state, hydrated } = useDemo();
  const shipments = useMemo(() => resolveShipments(base, state), [base, state]);
  return { shipments, hydrated };
}

export function usePreferences() {
  const { state, dispatch } = useDemo();
  return {
    preferences: state.preferences,
    setPreferences: (patch: Partial<Preferences>) =>
      dispatch({ type: "set-preferences", patch }),
  };
}

export function useNotifications() {
  const { state, dispatch } = useDemo();
  return {
    notifications: state.notifications,
    setNotifications: (patch: Partial<NotificationPrefs>) =>
      dispatch({ type: "set-notifications", patch }),
  };
}
